# -*- coding: utf-8 -*-
"""Regressao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK_ePrtlVNI8buuWwtaWFuyvuaZmzUm8
"""

!pip install plotly --upgrade

import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

base_plano_saude = pd.read_csv('plano_saude.csv')
base_plano_saude

x_plano_saude = base_plano_saude.iloc[:,0].values
x_plano_saude

""".iloc[x,y] -> serve para selecionar um conjunto de registros da base de dados em questão. x = representa as linhas que desejo selecionar (':' representa todas). y = representa a coluna que se deseja pegar

"""

y_plano_saude = base_plano_saude.iloc[:,1].values
np.corrcoef(x_plano_saude,y_plano_saude)

x_plano_saude.shape

x_plano_saude=x_plano_saude.reshape(-1,1) #Trasforma em uma matriz
x_plano_saude

from sklearn.linear_model import LinearRegression
regressor_plano_saude = LinearRegression()
regressor_plano_saude.fit(x_plano_saude,y_plano_saude)

"""#b0 ou b (y=ax+b) representa a altura da linha no grafico quando o x for 0
regressor_plano_saude.intercept_
"""

#b1 ou a
regressor_plano_saude.coef_

previsoes = regressor_plano_saude.predict(x_plano_saude)
previsoes

x_plano_saude.ravel()

grafico = px.scatter(x=x_plano_saude.ravel(), y=y_plano_saude)
grafico.add_scatter(x=x_plano_saude.ravel(), y=previsoes, name='Regressão Linear')
grafico.show()

regressor_plano_saude.score(x_plano_saude,y_plano_saude)

from yellowbrick.regressor import ResidualsPlot
visualizador = ResidualsPlot(regressor_plano_saude)
visualizador.fit(x_plano_saude,y_plano_saude)
visualizador.poof()

"""# **Iniciando Exercicio 2 (Preço casas)**

"""

base_casas = pd.read_csv('house_prices.csv')
base_casas

base_casas.isnull().sum()

base_casas.corr(numeric_only=True) #verifica a correlação de um atributo com todos os outros

figura = plt.figure(figsize=(20,20))
sns.heatmap(base_casas.corr(numeric_only=True), cmap='coolwarm', annot=True)

x_casas = base_casas.iloc[:,5:6].values
x_casas

y_casas = base_casas.iloc[:,2].values
y_casas

from sklearn.model_selection import train_test_split
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size=0.3, random_state=0)

x_casas_treinamento.shape, y_casas_treinamento.shape

x_casas_teste.shape, y_casas_teste.shape

from sklearn.linear_model import LinearRegression
regressor_simples_casas = LinearRegression()
regressor_simples_casas.fit(x_casas_treinamento,y_casas_treinamento)

regressor_simples_casas.intercept_

regressor_simples_casas.coef_

regressor_simples_casas.score(x_casas_treinamento, y_casas_treinamento)

regressor_simples_casas.score(x_casas_teste, y_casas_teste)

previsoes = regressor_simples_casas.predict(x_casas_treinamento)
previsoes

grafico = px.scatter(x=x_casas_treinamento.ravel(), y=previsoes)
grafico.show()

grafico1= px.scatter(x=x_casas_treinamento.ravel(), y=y_casas_treinamento)
grafico2=px.line(x = x_casas_treinamento.ravel(), y=previsoes)
grafico2.data[0].line.color='red'
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3

previsoes_teste = regressor_simples_casas.predict(x_casas_teste)
previsoes_teste

from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_casas_teste, previsoes_teste)

mean_squared_error(y_casas_teste, previsoes_teste)

grafico1= px.scatter(x=x_casas_teste.ravel(), y=y_casas_teste)
grafico2=px.line(x = x_casas_treinamento.ravel(), y=previsoes)
grafico2.data[0].line.color='red'
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3

x_casas_teste

"""# **Regressão multipla preço da casa**"""

x_casas = base_casas.iloc[:,3:19].values
x_casas

y_casas = base_casas.iloc[:,2].values
y_casas

from sklearn.model_selection import train_test_split
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size=0.3, random_state=0)

x_casas_treinamento.shape, x_casas_teste.shape

regressor_multiplo_casas = LinearRegression()
regressor_multiplo_casas.fit(x_casas_treinamento,y_casas_treinamento)

regressor_multiplo_casas.score(x_casas_treinamento,y_casas_treinamento)

regressor_multiplo_casas.score(x_casas_teste,y_casas_teste)

previsoes = regressor_multiplo_casas.predict(x_casas_teste)
previsoes

from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_casas_teste, previsoes)

